#!/bin/sh
MIDIR=/var/lib/mechanismimporter

# Create mechanism importer user
USER=$(id -u mechanismimporter &>/dev/null)
if [ ! $USER ]
then
	echo "Creating mechanismimporter user..."
	useradd -d /var/lib/mechanismimporter -s /bin/sh -U mechanismimporter
fi

# create logs dir
mkdir -p ${MIDIR}/logs/

# Use npm to install deps.  This should be in a package.json...
npm install --prefix ${MIDIR} synchronize
npm install --prefix ${MIDIR} xml2js
npm install --prefix ${MIDIR} fast-csv
npm install --prefix ${MIDIR} properties-reader

# Correct permissions on directory
chown -R mechanismimporter:mechanismimporter ${MIDIR}
